-- Fiókzárolás jelszavas brute-force ellen
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "failedLoginCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lockedUntil" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastFailedLoginAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastFailedLoginIp" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lockAlertSentAt" TIMESTAMP(3);
